### ISSUE TITLE
Export GShow' class name

### ISSUE THREAD

**Issue by jcpetruzza** [dreixel/generic-deriving#10]
Currently, if one uses `gshowsPrecdefault` in a generic function, the resulting type signature cannot be written (and one gets an warning with `-Wall`). A concrete usage example would be:

```
constructorOf x = head $ words $ gshowsPrecdefault 0 x []
```

**Comment by YLiLarry** [comment]
Hi, I'm working on a case where GShow' is useful:

I have a class named `Model`, I'm using Data.Aeson. If I want all instances of `Model` to automatically be an instance of `FromJSON` and `ToJSON`, I could write:
`
instance (Model a, Generic (a m), A.GToJSON (Rep (a m))) => A.ToJSON (a m)
instance (Model a, Generic (a m), A.GFromJSON (Rep (a m))) => A.FromJSON (a m)
`
Similarly, if I want all instances of `Model` to be instances of `GShow`, I was hoping to write:
`
instance (Model x, Generic (x a), GShow' (Rep (x a))) => GShow (x a)
`
