### ISSUE TITLE
Orphan instances for GHC < 7.1 don't match base

### ISSUE THREAD

**Issue by RyanGlScott** [dreixel/generic-deriving#13]
`generic-deriving` currently defines orphan `Generic`/`Generic1` instances for `Char`, `Float`, `Int`, `Maybe`, and `[]`, but they don't seem to line up with the instances that `base` provides:

* `base` [manually defines](http://hackage.haskell.org/package/base-4.8.0.0/docs/src/GHC-Generics.html#line-750) `Generic` instances for `Char` and `Int`, but they don't seem to match up with the [orphan instances](http://hackage.haskell.org/package/generic-deriving-1.7.0/docs/src/Generics-Deriving-Instances.html#line-44) in `generic-deriving` (e.g., `Rep Char = D1 D_Char (C1 C_Char (S1 NoSelector (Rec0 Char)))` in `base`, but `Rep Char = Rec0 Char` in `generic-deriving`).
* `base` has derived `Generic1` instances for `[]` and `Maybe`. These derived `Generic1` instances include meta-information that `generic-deriving`'s orphan `Generic1` instances do not. For example, in `generic-deriving`, `Rep1 Maybe = D1 Maybe_ (C1 Nothing_ U1 :+: C1 Just_ Par1)`, whereas the derived instance gives `Rep Maybe = D1  (C1 Nothing_ U1 :+: C1 Just_ (S1 NoSelector Par1))`.

Is this intentional?

**Comment by dreixel** [comment]
Hello,

Regarding the `Char` and `Int` instances: I've been wanting to remove those for a while, both from `base` and from `generic-deriving`. They are probably a bad idea, or just useless. Either way, they should match.

Regarding `[]` and `Maybe`: `generic-deriving` is just wrong here.

Would you care to submit a pull request? Thanks!

Pedro

**Comment by RyanGlScott** [comment]
I can make a pull request for this sometime soon.

One of the reason I'm asking about this is because I've also been looking into backporting `Generic(1)` instances back to GHC 7.2 and 7.4 as a part of the [`base-orphans`](http://hackage.haskell.org/package/base-orphans) package. My goal with `base-orphans` is to provide a common source for orphan instances (introduced by changes to `base`) to use with older versions of GHC, so that other packages don't have to define them (and possibly cause conflicts if a library has two dependencies with the same orphan instances).

Would you be alright if I had `generic-deriving` reexport these `base-orphans` instances from `Generic.Deriving.Instances`? I could simply copy the instance definitions over to make them compatible with GHC < 7.1 (which uses the redefined `GHC.Generics` machinery).

**Comment by dreixel** [comment]
You mean this would introduce a dependency on `base-orphans`?

**Comment by RyanGlScott** [comment]
Yes, that's what I had imagined. `base-orphans` doesn't (and will never) depend on anything more than `base` and `ghc-prim`, though.

**Comment by bergmark** [comment]
base-orphans + generic-deriving now contains the same orphan instances which caused the (as of now) latest log-domain to fail building on GHC 7.4 http://matrix.hackage.haskell.org/package/log-domain#GHC-7.4/log-domain-0.10.1

ping @ekmett

**Comment by ekmett** [comment]
Ugh. `generic-deriving` _is_ the official way to `Generic`/`Generic1` support on older compilers though, so it strikes me that this is more of an overreach of `base-orphans`.

**Comment by RyanGlScott** [comment]
Hm. I'm using quite a few of the `Generic`/`Generic1` instances from `base-orphans` in several of my libraries, so I'd rather not just remove them altogether. I'd be okay with removing the instances from `base-orphans` and using `generic-deriving` instead, but currently `generic-deriving` doesn't export all of the same `Generic` instances that `base-orphans` does (e.g., it has `Generic` instances for `Const`, `First`, `Last`, etc.).

@dreixel, would you be okay with either (1) adopting `base-orphans` and a dependency or (2) me amending pull request #14 to include all of the `Generic`/`Generic1` instances that `base` currently defines? Either approach should fix the instance conflicts while providing a way for users of older GHCs to use the same instances.

**Comment by sol** [comment]
Either way is fine with me as long as we end up with one canonical definition for those instances.

**Comment by RyanGlScott** [comment]
@bergmark @ekmett [`generic-deriving-1.8.0`](http://hackage.haskell.org/package/generic-deriving-1.8.0) and [`base-orphans-0.4.0`](http://hackage.haskell.org/package/base-orphans-0.4.0) have been released which (1) fixes this problem and (2) can safely be used together.

**Comment by bergmark** [comment]
@ekmett This fixed the log-domain build failure... didn't think it would!

**Comment by ekmett** [comment]
@RyanGIScott, @sol, @bergmark: Thanks!
