### ISSUE TITLE
Export deriveAll, etc. on all versions of GHC

### ISSUE THREAD

**Issue by RyanGlScott** [dreixel/generic-deriving#15]
I find the Template Haskelll deriving mechanism to be quite useful. Sometimes, it would be nice to use on GHC 7.2, where `StandaloneDeriving` and `DeriveGeneric` can't be used together due to a bug. Unfortunately, `generic-deriving` only exports `deriveAll` and related functions on GHC 7.1 and below, so I can't use TH in that case.

Can you remove the `#if __GLASGOW_HASKELL__ < 701` pragma so that TH can be used in lieu of `DeriveGeneric` bugs?

**Comment by dreixel** [comment]
I'm totally fine with that. Would you care to submit a pull request? Thanks!
