### ISSUE TITLE
Make it easier to install generic-deriving on TH-less GHCs

### ISSUE THREAD

**Issue by hvr** [dreixel/generic-deriving#27]
Currently `Generics.Deriving.TH` requires a GHC with TH. So it's problematic for cross-compiling packages and/or when using an unregisterised GHC (which both lack TH).

I suggest to either

 a) get rid of the TH requirement (depending on `template-haskell` is ok, it's just `-XTemplateHaskell` that doesn't work

or

 b) add a manual cabal flag (c.f. how `QuickCheck` names that flag) that allows to build the package without TH

**Comment by RyanGlScott** [comment]
I think the HEAD version of `generic-deriving` has what you want since a2032478893c3bca815849aa002520fcd5faeb8e. Can you confirm?

**Comment by hvr** [comment]
@RyanGlScott indeed... you're one step ahead it seems :)
