### ISSUE TITLE
duplicate elements generated by `GEnum Word{8,16,32,64}` instances

### ISSUE THREAD

**Issue by hvr** [dreixel/generic-deriving#34]
I'm afraid there's still something not quite right:

```
> length (genum :: [Word8])
512
```

I'd expect `(genum :: [Word8]) == [minBound .. maxBound]` for unsigned fixed-width types...

Or more generally (this holds for Int{8,16,32,64} at least it seems):

```
prop_bounded_ints :: (Bounded a, Enum a, Ord a, GEnum a) -> Bool
prop_bounded_ints = Data.List.sort (genum :: [a]) == [minBound .. maxBound]
```

**Comment by RyanGlScott** [comment]
This should be fixed as of d82c53f514ce3dccf04bb3ddc2780e6365adb72f.
