### ISSUE TITLE
Doesn't build with template-haskell-2.11.0.0

### ISSUE THREAD

**Issue by ozgurakgun** [dreixel/generic-deriving#41]
The package doesn't build with template-haskell-2.11.0.0 (on older GHCs) even though the cabal file allows it.

The following command fails with GHC-7.8.4 and GHC-7.10.3, but succeeds with GHC-8.0.1.

```
cabal install generic-deriving-1.10.4.1 template-haskell-2.11.0.0
```

**Comment by RyanGlScott** [comment]
Why on Earth are you manually installing `template-haskell`? `template-haskell` is tightly coupled to the GHC version it is released with, so if you're using GHC 7.8, you should be using `template-haskell-2.9`, and if you're using GHC 7.10, you should be using `template-haskell-2.10`. Period. Trying to install a version of `template-haskell` that doesn't support your version of GHC is asking for trouble.

**Comment by ozgurakgun** [comment]
Wow, that is a stronger response than what I was expecting.

I don't know why but as part of a larger installation plan cabal-install (in a sandbox) is choosing to install a newer version of template-haskell. So I am not explicitly forcing it to use the latest version or anything like that.

Wouldn't you agree that generic-deriving should disallow versions of its dependencies if it's known not to work with them?

I realise this is going to be non-trivial, since template-haskell-2.11.0.0 is supported with GHC-8.

**Comment by RyanGlScott** [comment]
I apologize for the tone of my earlier comment—that came across as harsher than I intended. `template-haskell` really is a special package, just like `base`. If `cabal-install` is trying to install it as part of a build plan, then something has gone horribly wrong.

Now that I look, I can understand why that might have happened. The [Hackage metadata](http://hackage.haskell.org/package/template-haskell-2.11.0.0) for `template-haskell-2.11.0.0` has way too lenient lower bounds on `base`. It should only ever be allowed to install with `base-4.9`. @hvr, can this be made so?

**Comment by RyanGlScott** [comment]
@hvr [`ghc-boot`](http://hackage.haskell.org/package/ghc-boot-8.0.1) and [`ghc-boot-th`](http://hackage.haskell.org/package/ghc-boot-th-8.0.1) perhaps out to be corrected as well.

**Comment by hvr** [comment]
@RyanGlScott I had all those packages deliberately with as wide bounds as possible (after all, we need those bounds to be that way as otherwise you couldn't even bootstrap GHC!), and we tought `cabal-install` to allow `template-haskell` to be reinstalled (after it had been originally disallowed). And we're even considering allowing `base` to be reinstalled! Anyway, I have to investigate to figure out what the proper fix here is.

**Comment by RyanGlScott** [comment]
@ozgurakgun Until then, do you mind sharing what you are trying to install? I'm curious to know what the build plan is.

**Comment by ozgurakgun** [comment]
@RyanGlScott I created a minimal cabal file, it's [here](https://gist.github.com/ozgurakgun/2b02ad398f1bbb58400dd5c20eb8edea). Hope it helps.

**Comment by RyanGlScott** [comment]
Thanks, @ozgurakgun! That helps a lot.

I've pushed two commits recently which I believe should address this issue. (I successfully built `generic-deriving` using your `.cabal` file, for instance.) Can you verify that the HEAD version of `generic-deriving` works for your needs?

**Comment by ozgurakgun** [comment]
Seems to work. Please feel free to reject #42 and make a release if you like. Thanks!

**Comment by RyanGlScott** [comment]
Uploaded [`generic-deriving-1.10.6`](http://hackage.haskell.org/package/generic-deriving-1.10.6) to Hackage.

**Comment by ozgurakgun** [comment]
Thanks for the release @RyanGlScott. Unfortunately, it seems QuickCheck-2.8.2 has the same problem. Maybe this is better solved at the template-haskell level as you initially suggested.

**Comment by RyanGlScott** [comment]
Have you tried the recently published [`QuickCheck-2.9`](http://hackage.haskell.org/package/QuickCheck-2.9), by any chance? It's supposed to have a [fix for a similar issue](https://github.com/nick8325/quickcheck/issues/99).

**Comment by ozgurakgun** [comment]
I may have caused that release :)

**Comment by RyanGlScott** [comment]
Heh, I didn't even notice [that](https://github.com/nick8325/quickcheck/issues/101). :)

It's a bit hard for me to notice these kinds of issues, since I almost never try to depend on the latest version of packages like `pretty` (since `pretty` is a GHC boot library). I suppose the best programmer discipline is to avoid using `#if __GLASGOW_HASKELL__ > ...` whenever possible.
