### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage

### ISSUE THREAD

**Issue by expipiplus1** [dreixel/generic-deriving#45]
The documentation for the latest version of this package is missing on Hackage. They've been pending on Hackage for some time, this usually indicated that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please?

Thanks!

**Comment by RyanGlScott** [comment]
[Done](http://hackage.haskell.org/package/generic-deriving-1.11.1).

**Comment by expipiplus1** [comment]
Thanks.
