### ISSUE TITLE
Feature Request: Eq1 and Ord1

### ISSUE THREAD

**Issue by andrewthad** [dreixel/generic-deriving#46]
The `Eq1` and `Ord1` classes provided by `base` would be good candidates for the kind of things this package offers. I cannot offer to write them at this time, but I thought I would bring it up.

**Comment by RyanGlScott** [comment]
Keep in mind that `generic-deriving` doesn't actually derive any classes in `base`. For instance, we cover `GEq`, which is spiritually quite close to `Eq`, but not quite `Eq`. (Actually covering all the classes in `base` would pose some issues for this package's no-dependencies policy—e.g., `Semigroup`). So to fulfill your request, we'd have to add something like `GEq1` and `GOrd1`.

In the meantime, there are some alternatives:
* `transformers-compat` has a (yet-unreleased-to-Hackage) module called [`Data.Functor.Classes.Generic`](https://github.com/ekmett/transformers-compat/blob/01453c3e73be66a4c685df86f96bee4c19ca686b/generics/Data/Functor/Classes/Generic.hs), which derives `Eq1`, `Ord1`, `Read1`, and `Show1`. If you want to see that released soon, I encourage you to drop the owner of that repo a line :)
* [`deriving-compat`](http://hackage.haskell.org/package/deriving-compat) can derive all of those classes too, but with `template-haskell`

**Comment by andrewthad** [comment]
The `Data.Functor.Classes.Generic` module looks like exactly what I'm looking for. I've opened up an issue to have it released to hackage. Also, when you say:

> For instance, we cover GEq, which is spiritually quite close to Eq, but not quite Eq

What exactly does that mean? Couldn't someone write:

    data Foo = ...
      deriving (Generic)
    instance Eq Foo where (==) = geq

**Comment by RyanGlScott** [comment]
> What exactly does that mean? Couldn't someone write:
> 
> ```
> data Foo = ...
>   deriving (Generic)
> instance Eq Foo where (==) = geq
> ```

Not in every case, no. For instance, if you had:

```haskell
newtype Foo a = Foo a

instance Eq a => Eq (Foo a) where
  (==) = geq
```

That wouldn't work, since that would impose a `GEq a` constraint, not an `Eq a` constraint.

And for the most part, the classes in this package are designed to be educational rather than exact mimics of their counterparts in `base`. A notable example of this is `GEnum`, which behaves quite differently than `Enum` as the former can be derived for more datatypes than the former (even encompassing sum and product types).

**Comment by andrewthad** [comment]
Ah, gotcha. That totally makes sense. Thanks.

**Comment by int-index** [comment]
@RyanGlScott What package do I use if I need `Generic` deriving for `Eq`, not `GEq`?

**Comment by int-index** [comment]
My workaround so far are these orphan instances:

```
instance {-# OVERLAPPABLE #-} Eq a => GEq a where
  geq = (==)

instance {-# OVERLAPPABLE #-} Show a => GShow a where
  gshowsPrec = showsPrec
```

**Comment by RyanGlScott** [comment]
@int-index: No such package exists, to my knowledge.
