### ISSUE TITLE
Implement mconcatdefault

### ISSUE THREAD

**Issue by expipiplus1** [dreixel/generic-deriving#50]
It might be handy to have `mconcatdefault` defined!

**Comment by RyanGlScott** [comment]
Do you have a use case for this? `mconcat` already has a default definition, and I doubt that implementing `mconcat` via `GHC.Generics` would be any more performant (in fact, it'd likely be _worse_).

**Comment by expipiplus1** [comment]
I don't have a use case for this at the moment, just crossed my mind when using this package.

One use case could be for the monoid instance for a product type containing a member which has a significantly faster `mconcat`. Without looking, I couldn't say whether any of the instances of `GMonoid` satisfy this property though...

I'm happy to close this if this isn't the case.

**Comment by RyanGlScott** [comment]
> One use case could be for the monoid instance for a product type containing a member which has a significantly faster `mconcat`.

I'm not sure what you mean here. The default definition of `mconcat` is literally just `foldr mappend mempty`, so to my knowledge, we never recursively call `mconcat`.

**Comment by expipiplus1** [comment]
Yeah, I've just looked: None of the instances of `GMonoid` have a faster `mconcat`, so this is almost certainly not a win.
