### ISSUE TITLE
Build error on GHC 8.4.1-alpha1

### ISSUE THREAD

**Issue by asr** [dreixel/generic-deriving#51]
Using the current master (commit 331dfa0) I got the following error on GHC 8.4.1-alpha1:

```
cabal install
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: generic-deriving-1.12 (user goal)
next goal: template-haskell (dependency of generic-deriving-1.12)
rejecting: template-haskell-2.13.0.0/installed-2.1... (conflict:
generic-deriving => template-haskell>=2.4 && <2.13)
```

The error can be fixed by allowing template-haskell 2.13. 

Note that the Travis [build](https://travis-ci.org/dreixel/generic-deriving/builds/326151850) on GHC 8.4.1 doesn't report this error.

Blocking https://github.com/agda/agda/issues/2878.

**Comment by asr** [comment]
CC'ing @RyanGlScott.

**Comment by RyanGlScott** [comment]
I've made a [revision](https://hackage.haskell.org/package/generic-deriving-1.12.1/revisions/) on Hackage.

**Comment by asr** [comment]
Great! Thanks!
