### ISSUE TITLE
Newtype(s) to support DerivingVia

### ISSUE THREAD

**Issue by dbaynard** [dreixel/generic-deriving#58]
Following MuniHac I've been learning to use `DerivingVia`. As some of my newtypes just use the default implementations, it might make sense to export them from this library (at no maintainance cost for pre-8.6 GHC).

Edit: Actually, it makes sense to have a single `newtype Default a = Default a` for any implementation which just uses the defaults.

I've only just started with this, but I believe most, if not all, classes in this library would benefit from this. Happy to PR.

---

For example, for `Eq`:

```haskell
newtype AsEq a = AsEq a

instance (Generic a, GEq' (G.Rep a)) => Eq (AsEq a) where
  AsEq x == AsEq y = x `geqdefault` y

instance (Generic a, GEq' (G.Rep a)) => GEq (AsEq a) where
  AsEq x `geq` AsEq y = x `geqdefault` y
```

And for `Enum`:

```haskell
newtype AsEnum a = AsEnum a

instance (Generic a, GEq a, Enum' (G.Rep a)) => Enum (AsEnum a) where
  toEnum = AsEnum . toEnumDefault
  fromEnum (AsEnum x) = fromEnumDefault x

instance (Generic a, GEq a, Enum' (G.Rep a)) => GEnum (AsEnum a) where
  genum = AsEnum . G.to <$> enum'
```

Then I can simply add the following, to use the default implementations without needing to explicitly write out the `where geq = geqdefault` line.

```haskell
deriving via (AsEq MyEnum) instance GEq MyEnum

deriving via (AsEnum MyEnum) instance Enum MyEnum
```

My example is in https://github.com/dbaynard/generic-programming-munihac-2018/tree/record — I'm investigating how much ancilliary information I can ergonomically fit into type definitions.

**Comment by dbaynard** [comment]
Actually, I could combine them all into a single, `Default` newtype.

**Comment by RyanGlScott** [comment]
Sounds like a good idea to me! I'd happily accept a pull request implementing this idea.

You might also consider having another newtype for `GFunctor`, `GFoldable`, `GTraversable`, and `GCopoint`, since those classes have different kinds than the others.

**Comment by dbaynard** [comment]
I've done the `Default` instances at https://github.com/dbaynard/generic-deriving/tree/feat/deriving-via.

Instances for the higher kinded classes are in progress.

**Comment by RyanGlScott** [comment]
Sounds promising! Can you submit a pull request?

In response to your points:

1. Exporting internal types is fine—we already export several of them already.
2. I'm not sure exactly what you mean here, but perhaps this would become clearer if I could see the code in a PR.
3. While I appreciate the offer, this library has a very wide support window (back to GHC 7.0), so I'd prefer not to incur additional dependencies if I can avoid it. (I'm already depending on `hspec`, so we can at least test some things.)
4. Again, I'm not sure what you mean by "get rid of the various helper classes".

**Comment by dbaynard** [comment]
2. I'll PR now.

4. I meant, it implements, say, `Functor`, but using neither `GFunctor` nor `GFunctor'`, for use with `DerivingVia`. These `Default` data types could actually then be implemented in a separate package, which would not depend on this package. If the performance is the same, this PR wouldn't be as desirable.

**Comment by RyanGlScott** [comment]
> I meant, it implements, say, `Functor`, but using neither `GFunctor` nor `GFunctor'`, for use with `DerivingVia`. These `Default` data types could actually then be implemented in a separate package, which would not depend on this package. If the performance is the same, this PR wouldn't be as desirable.

Ah, I see what you mean. Yes, personally speaking, I would prefer that we only handle the `G` classes. The way I see it, the classes in this library are mostly provided for pedagogical purposes so as to provide simple examples of datatype-generic programming. If one wanted to derive, say, `Functor`, I would encourage them to use the [`generic-data`](http://hackage.haskell.org/package/generic-data) library instead, which doesn't have the same dependency footprint/backwards compatibility constraints as this library.
