### ISSUE TITLE
Failure with GHC 8.8 / template-haskell 2.15.0

### ISSUE THREAD

**Issue by deepfire** [dreixel/generic-deriving#60]
```
[13 of 20] Compiling Generics.Deriving.TH.Internal ( src/Generics/Deriving/TH/Internal.hs, dist/build/Generics/Deriving/TH/Internal.o )

src/Generics/Deriving/TH/Internal.hs:459:22: error:
    • Couldn't match type ‘TyVarBndr’ with ‘Type’
      Expected type: Q (Either
                          String (Name, [Type], [ConstructorInfo], DatatypeVariant_))
        Actual type: Q (Either
                          [Char] (Name, [TyVarBndr], [ConstructorInfo], DatatypeVariant_))
    • In the expression:
        do return $ Left $ ns ++ " Could not reify " ++ nameBase name
          `recover`
            do DatatypeInfo {datatypeContext = ctxt, datatypeName = parentName,
                             datatypeVars = tys, datatypeVariant = variant,
                             datatypeCons = cons} <- reifyDatatype name
               let variant_ = ...
               checkDataContext parentName ctxt
                 $ Right (parentName, tys, cons, variant_)
      In an equation for ‘reifyDataInfo’:
          reifyDataInfo name
            = do return $ Left $ ns ++ " Could not reify " ++ nameBase name
                `recover`
                  do DatatypeInfo {datatypeContext = ctxt, datatypeName = parentName,
                                   datatypeVars = tys, datatypeVariant = variant,
                                   datatypeCons = cons} <- reifyDatatype name
                     let variant_ = ...
                     checkDataContext parentName ctxt
                       $ Right (parentName, tys, cons, variant_)
            where
                ns :: String
                ns = "Generics.Deriving.TH.reifyDataInfo: "
    |
459 | reifyDataInfo name = do
    |                      ^^...
```

**Comment by RyanGlScott** [comment]
How are you building this? `generic-deriving-1.12.2` should build fine using the [latest `head.hackage` commit](https://github.com/hvr/head.hackage/tree/6f2c86bdf5e64096c770c67bd156d1c62ec5c9cb).

**Comment by RyanGlScott** [comment]
I'm especially confused here since the error message mentions `TyVarBndr`, which shouldn't happen. You aren't using a pre-release version of `th-abstraction-0.3.0.0`, are you?

**Comment by deepfire** [comment]
@RyanGlScott, oh, I am, indeed, using heavy overrides from git HEAD's all over the place.

I guess I need to figure out versions better.

Thank you, and sorry for the confusion!

**Comment by deepfire** [comment]
Speaking of pointless projects: https://github.com/deepfire/nix-head

The idea is to take `head.hackage` and build on top of it a low-friction Nix-based workbench for overrides -- with the notion that overrides subsume patching (by allowing more flexibility).

This can be used as staging ground for patch development.

**Comment by RyanGlScott** [comment]
Cool! If I ever force myself to learn Nix, `nix-head` would be a valuable resource.

Assuming that that works for you, is there actually a problem to be addressed here? Or can I close this issue?

**Comment by deepfire** [comment]
Let's close it for now, and in case something goes wrong, I can always reopen : -)

**Comment by Fuuzetsu** [comment]
I also hit this, I'm trying to build something with GHC HEAD and this is in the way… I'll try to hack around it but it'd be cool if patches started making it in ahead of time.

**Comment by RyanGlScott** [comment]
Do note that [`generic-deriving-1.12.3`](http://hackage.haskell.org/package/generic-deriving-1.12.3) features a fix for the build error observed in https://github.com/dreixel/generic-deriving/issues/60#issue-402919774.
