### ISSUE TITLE
Make GMonoid a subclass of GSemigroup?

### ISSUE THREAD

**Issue by sjakobi** [dreixel/generic-deriving#64]
I'm not sure whether this is actually important. I just noted that it wasn't the case yet.

**Comment by RyanGlScott** [comment]
I pondered this in #33, but I backed off at the time since that would have required breaking changes. That being said, we've already introduced a breaking change in #63, so perhaps this is a good time to finally follow through on this plan.

**Comment by sjakobi** [comment]
Cheers! :)
