### ISSUE TITLE
genum ordering of sum types

### ISSUE THREAD

**Issue by mulderr** [dreixel/generic-deriving#86]
Hi, on GHC 9.2.2:

```
ghci> data MyEnum = A | B | C | D | E deriving (Show, Generic, GEnum)
ghci> genum @MyEnum
[A,C,B,D,E]
```

If we change `|||` to `++` [here](https://github.com/mulderr/generic-deriving/blob/ec2fff74da0d6051d3c88613e324cf94d571c7b9/src/Generics/Deriving/Enum.hs#L130) we get the intuitive order and all tests still pass. I suspect `|||` is there for good reason, but I'm not sure what that is and the above result seems somewhat unexpected - or is it?

**Comment by RyanGlScott** [comment]
The use of `(|||)` was motivated by [these lecture notes](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.158.23&rep=rep1&type=pdf). The idea is that if you run `genum @Int [minBound .. maxBound]`, then the beginning of the list would be heavily biased towards negative numbers, so `(|||)` is used to alternate between positive and negative numbers.

That being said, this behavior may not be what you would want, and it is quite reasonable to want a different `GEnum` implementation that uses `(++)` instead. Ultimately, the `GEnum` class (like all of the `G`-prefixed classes in this library) are meant to be educational examples, so please adapt them as you see fit to your use case.

**Comment by RyanGlScott** [comment]
In fact, such an `(++)`-based implementation already exists in the [`generic-data`](https://hackage.haskell.org/package/generic-data-1.0.0.0/docs/Generic-Data-Internal-Enum.html) library, now that I look closer.

**Comment by mulderr** [comment]
Thanks for a quick response! That makes perfect sense. I'll check out `generic-data`.

I guess I got a overeager after reading [this](https://typeclasses.com/phrasebook/invert) and missed the "educational examples" bit in the documentation.
